### PR TITLE
Update for Tapestry 5.4

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by jochenberger** [comment]
fixes #7

**Comment by jochenberger** [comment]
and #27

**Comment by uklance** [comment]
Thanks v. much for your contribution. I've merged your pull request and created an [0.0.6 release](https://github.com/uklance/releases/tree/master/org/lazan/tapestry-atmosphere/0.0.6)

**Comment by jochenberger** [comment]
Great. You could also close #7 and #27 since they are addressed by the PR too.

**Pull request merged**
